### ISSUE TITLE
Changement de prix

### ISSUE THREAD

**Issue by apuyou** [payutc/scoobydoo#12]
Le changement de prix n'est pas encore codé.

À vue de nez, il faut conserver l'ancien prix mais le passer en removed et ajouter un nouveau prix que l'on associe à l'article. Mais est-ce que les fonctions qui manipulent les articles (liste des articles, transactions, export CA...) savent gérer un prix removed ?

**Comment by mattgu74** [comment]
Je pense qu'on devrais revoir la table price,

Pour ajouter les colonnes suivantes:
heure_début
heure_fin
=> Permettre d'indiquer la période horaire sur laquelle s'applique le price.

date_ajout
=> Permettre de connaitre à partir de quel date ce prix à été instauré

Modification
removed (bool => datetime)
=> Permettre de connaitre à partir de quel date un prix à été supprimé.

(Comme ça après on peut faire des graphs de l'évolution des prix en
fonctions des années...)
(Et on peut appliquer des tarifs différents en fonction des heures)

Après les modifications dans la table, il faut revoir les services.
En effet la modification que je propose, implique de revoir pas mal de
chose derrière.

On peut continuer d'exposer AADMIN en checkant juste removed = NULL et en
laissant les heures de période à NULL (bref pour rester compatible avec
scoobydoo)
Et commencer à créer le nouveau service de gestion des articles avec toutes
les methodes de gestion "plus fine" que l'on introduit. Et une fois que les
services seront codés on pourra créer scoobydoo V2.

etc...
