### ISSUE TITLE
Impossible d'ajouter des droits

### ISSUE THREAD

**Issue by trecouvr** [payutc/scoobydoo#34]
J'ai essayé d'ajouter à vincent pepin (pepinvin) le droit "administrateur de fondation" sur "festupic" : impossible, scoobydoo me dit succès mais quand je recharge la page le droit n'est pas mis.

**Comment by mattgu74** [comment]
Je viens de l'ajouter aucun problème...

PS: Il ne faut pas entrer le login, mais le prénom ou le nom et cliquer sur la liste déroulante.
PS2: Le pic à bien réussi à mettre tout ces membres, c'est bien que ça marche.
