### ISSUE TITLE
Intégrer la gestion de la TVA

### ISSUE THREAD

**Issue by vincentlaine** [payutc/scoobydoo#39]
Je m'incruste pour vous relancer sur ce point car ça fait un peu un an qu'on vous le demande : 
- intégrer une gestion de la TVA qui pourra être rentrée par les utilisateurs de la fundation Pic'asso (car je crois que ça ne servira qu'à nous), ou bien faire un truc fixe qui défini que dans un article de la catégorie "Bière" dans le prix entré il y a 19,6% de TVA et 7% pour toutes les autres catégories (softs, snacks, perms etc ...).
- Afficher la TVA sur le ticket
- Intégrer la TVA dans l'export du CA

Ce serait cool que ce soit près rapidement même si on est pas ouvert au semestre pro car sinon ça va encore traîner longtemps ...

**Comment by apuyou** [comment]
Voir aussi https://github.com/payutc/server/issues/103

**Comment by mattgu74** [comment]
Je ne sais pas ce qu'en pense Arthur, mais je pense qu'on fera ça au mois
de juillet pendant nos séances intensives de dev sur payutc.

**Comment by apuyou** [comment]
Tout à fait pour, le premier ticket est assez récent mais ils réclament depuis longtemps.

Il faudra bien insister sur le fait que payutc se contente juste de calculer la TVA pour le compte de l'asso, mais que ce n'est pas payutc qui la reverse.

**Comment by vincentlaine** [comment]
Evidemment, ce sera toujours le Pic'asso qui paiera la TVA (on est pas si
méchant quand même).

Le 23 juin 2013 23:49, Arthur Puyou notifications@github.com a écrit :

> Tout à fait pour, le premier ticket est assez récent mais ils réclament
> depuis longtemps.
> 
> Il faudra bien insister sur le fait que payutc se contente juste de
> calculer la TVA pour le compte de l'asso, mais que ce n'est pas payutc qui
> la reverse.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/payutc/scoobydoo/issues/39#issuecomment-19882301
> .

## 

Vincent Lainé
Étudiant en Tronc Commun
Université Technologique de Compiègne
+33 6 69 98 69 40
