### ISSUE TITLE
Upload d'image pour un article

### ISSUE THREAD

**Issue by mattgu74** [payutc/scoobydoo#5]
Le serveur peut gérer les images, ce serait bien de pouvoir les uploader depuis scoobydoo.

Une fois que ce ticket sera réalisé, il faudra voir pour utiliser les images dans : 
- Scoobydoo (affichage à coté de l'article) (ça sa va avec ce ticket)
- Mozart
- Pauline
- Casper (au survol des articles dans l'historique ?)

**Comment by apuyou** [comment]
Il y a également la fonction à faire côté serveur : https://github.com/payutc/server/issues/6
