### ISSUE TITLE
Regrouper les users dans le tableau d'affichage des droits

### ISSUE THREAD

**Issue by mattgu74** [payutc/scoobydoo#6]
Sur la page droits, il y'a une ligne par user et par droit... Genre au pic ça fait un truc énorme...
Faudrait avoir une ligne par user et afficher tout les droits que cet user à ce serait beaucoup plus propre et plus lisible.

**Comment by apuyou** [comment]
Le souci est que l'inverse est utile aussi (genre voir qui a le droit X).

Je propose un filtrage rapide pour améliorer l'UI, genre
http://datatables.net

Arthur Puyou

2012/11/8 Matthieu Guffroy notifications@github.com

**Comment by mattgu74** [comment]
Je pense qu'il est quand même plus fréquent de vérifier si tel personne à tout les droits qu'elle doit avoir. Que de regarder toutes les personnes qui ont le droit X.

Pour moi quand tu vérifies toutes les personnes qui ont le droit X c'est que c'est un début de semestre... Du coup tu supprimes tout les droits de tout le monde et tu ajoutes un par un et c'est plutôt cool de voir que tout tes membres ont 2droits (Vendre + gesarticle) (pour le pic par exemple) puis de voir que tes treso ont le droit treso en plus et ton bureau le droit admin... 

Enfin pour moi l'affichage "fusionné" est plus utile que l'affichage "ligne par ligne".

**Comment by apuyou** [comment]
Au Polar, j'aimais bien vérifier, même en cours de semestre, qu'on n'était
que deux à avoir le droit sur la gestion du coffre.

Arthur Puyou

2012/11/8 Matthieu Guffroy notifications@github.com

**Comment by mattgu74** [comment]
J'ai géré ce ticket dans la gestion des droits V2.
L'ancien module droit étant voué à la disparition quand AADMIN sera splitté... ce ticket n'a plus lieu d'être.
