### ISSUE TITLE
Pouvoir modifier le pied de ticket

### ISSUE THREAD

**Issue by apuyou** [payutc/scoobydoo#9]
Pouvoir changer des réglages d'une fundation quand on est admin dessus, notamment le pied de ticket.

Voir https://github.com/payutc/server/issues/52

**Comment by alecalve** [comment]
Je suis dessus et je vois pas comment accèder à MADMIN à partir de scoobydoo

**Comment by mattgu74** [comment]
Tu n'as pas à accéder à MADMIN depuis scoobydoo.

Faut que tu crées un nouveau service qui correspond au droit "gestion de pied de ticket".

Et ouvrir des méthodes aux gens qui ont les droits sur une fundation...

**Comment by mattgu74** [comment]
Look un peu le service et le module BLOCAGE, c'est à peu près ce que tu dois faire sur toute la ligne (mais pour des messages perso au lieu de blocage bien sur...)

**Comment by mattgu74** [comment]
done
